blank_issues_enabled: false
contact_links:
  - name: 코드 리뷰 컨벤션
    url: https://jehye.atlassian.net/wiki/spaces/MA/pages/4096005/PR
    about: Issue와 PR 작성 전에 팀 컨벤션을 화인하세요.
