"""API명세서.md 도메인(mock persona 기반) 신규 테이블."""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "20260816_0002"
down_revision: str | None = "20260814_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "generations",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("persona_id", sa.String(length=30), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_generations")),
    )
    op.create_index(op.f("ix_generations_persona_id"), "generations", ["persona_id"], unique=False)
    op.create_table(
        "idempotency_records",
        sa.Column("scope", sa.String(length=100), nullable=False),
        sa.Column("subject", sa.String(length=100), nullable=False),
        sa.Column("key", sa.String(length=200), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=False),
        sa.Column("response_body", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_idempotency_records")),
        sa.UniqueConstraint("scope", "subject", "key", name=op.f("uq_idempotency_records_scope")),
    )
    op.create_index(
        op.f("ix_idempotency_records_scope"), "idempotency_records", ["scope"], unique=False
    )
    op.create_index(
        op.f("ix_idempotency_records_subject"), "idempotency_records", ["subject"], unique=False
    )
    op.create_table(
        "ingredients",
        sa.Column("id", sa.String(length=60), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("risk_level", sa.String(length=10), nullable=False),
        sa.Column("target_concern", sa.String(length=200), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingredients")),
        sa.UniqueConstraint("name", name=op.f("uq_ingredients_name")),
    )
    op.create_table(
        "knowledge_documents",
        sa.Column("source_url", sa.String(length=500), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("license", sa.String(length=100), nullable=True),
        sa.Column("source_type_note", sa.String(length=300), nullable=True),
        sa.Column("review_status", sa.String(length=20), nullable=False),
        sa.Column("claim_id", sa.String(length=60), nullable=True),
        sa.Column("claim_version", sa.Integer(), nullable=True),
        sa.Column("topic", sa.String(length=100), nullable=True),
        sa.Column("population", sa.String(length=200), nullable=True),
        sa.Column("evidence_level", sa.String(length=20), nullable=True),
        sa.Column("allowed_features", sa.JSON(), nullable=True),
        sa.Column("required_user_facts", sa.JSON(), nullable=True),
        sa.Column("allowed_expressions", sa.String(length=500), nullable=True),
        sa.Column("forbidden_expressions", sa.String(length=500), nullable=True),
        sa.Column("next_review_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_documents")),
    )
    op.create_table(
        "knowledge_indexes",
        sa.Column("version", sa.String(length=30), nullable=False),
        sa.Column("claim_ids", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_indexes")),
        sa.UniqueConstraint("version", name=op.f("uq_knowledge_indexes_version")),
    )
    op.create_table(
        "personas",
        sa.Column("id", sa.String(length=30), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("summary_traits", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_personas")),
    )
    op.bulk_insert(
        sa.table(
            "personas",
            sa.column("id", sa.String),
            sa.column("label", sa.String),
            sa.column("summary_traits", sa.JSON),
        ),
        [
            {
                "id": "persona_001",
                "label": "복합성·트러블 케어",
                "summary_traits": {
                    "skin_type": "복합성",
                    "primary_concern": "cn_acne",
                    "notes": "T존 유분과 트러블이 함께 나타나는 편이에요.",
                },
            },
            {
                "id": "persona_002",
                "label": "건성·민감 케어",
                "summary_traits": {
                    "skin_type": "건성",
                    "primary_concern": "cn_dryness",
                    "notes": "환절기에 당김과 붉은기가 심해지는 편이에요.",
                },
            },
            {
                "id": "persona_003",
                "label": "생리 주기 트러블 케어",
                "summary_traits": {
                    "skin_type": "지성",
                    "primary_concern": "cn_hormonal",
                    "notes": "생리 전후로 턱선 트러블이 반복돼요.",
                },
            },
        ],
    )
    op.create_table(
        "recommendation_products",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("brand", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("external_url", sa.String(length=500), nullable=False),
        sa.Column("safety_policy_note", sa.String(length=300), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recommendation_products")),
        sa.UniqueConstraint("brand", "name", name=op.f("uq_recommendation_products_brand")),
    )
    op.create_table(
        "briefings",
        sa.Column("persona_id", sa.String(length=30), nullable=False),
        sa.Column("briefing_date", sa.Date(), nullable=False),
        sa.Column("generation_id", sa.String(length=64), nullable=False),
        sa.Column("risk_level", sa.String(length=20), nullable=False),
        sa.Column("headline", sa.String(length=200), nullable=False),
        sa.Column("summary", sa.String(length=500), nullable=False),
        sa.Column("contributing_factors", sa.JSON(), nullable=False),
        sa.Column("routine", sa.JSON(), nullable=False),
        sa.Column("skip", sa.JSON(), nullable=False),
        sa.Column("common_knowledge", sa.JSON(), nullable=True),
        sa.Column("data_coverage", sa.JSON(), nullable=False),
        sa.Column("limitation_notice", sa.String(length=300), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["persona_id"],
            ["personas.id"],
            name=op.f("fk_briefings_persona_id_personas"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_briefings")),
        sa.UniqueConstraint("generation_id", name=op.f("uq_briefings_generation_id")),
        sa.UniqueConstraint("persona_id", "briefing_date", name=op.f("uq_briefings_persona_id")),
    )
    op.create_index(op.f("ix_briefings_persona_id"), "briefings", ["persona_id"], unique=False)
    op.create_table(
        "consents",
        sa.Column("persona_id", sa.String(length=30), nullable=False),
        sa.Column("type", sa.String(length=30), nullable=False),
        sa.Column("consented", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["persona_id"],
            ["personas.id"],
            name=op.f("fk_consents_persona_id_personas"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_consents")),
        sa.UniqueConstraint("persona_id", "type", name=op.f("uq_consents_persona_id")),
    )
    op.create_index(op.f("ix_consents_persona_id"), "consents", ["persona_id"], unique=False)
    op.create_table(
        "daily_metrics",
        sa.Column("persona_id", sa.String(length=30), nullable=False),
        sa.Column("metric_date", sa.Date(), nullable=False),
        sa.Column("hydration_level", sa.String(length=20), nullable=True),
        sa.Column("diet_flag", sa.String(length=30), nullable=True),
        sa.Column("sleep_hours", sa.Float(), nullable=True),
        sa.Column("hrv_ms", sa.Float(), nullable=True),
        sa.Column("active_energy_kcal", sa.Float(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["persona_id"],
            ["personas.id"],
            name=op.f("fk_daily_metrics_persona_id_personas"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_daily_metrics")),
        sa.UniqueConstraint("persona_id", "metric_date", name=op.f("uq_daily_metrics_persona_id")),
    )
    op.create_index(
        op.f("ix_daily_metrics_persona_id"), "daily_metrics", ["persona_id"], unique=False
    )
    op.create_table(
        "generation_feedback",
        sa.Column("generation_id", sa.String(length=64), nullable=False),
        sa.Column("persona_id", sa.String(length=30), nullable=False),
        sa.Column("rating", sa.String(length=20), nullable=False),
        sa.Column("reason_code", sa.String(length=40), nullable=True),
        sa.Column("comment", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["generation_id"],
            ["generations.id"],
            name=op.f("fk_generation_feedback_generation_id_generations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["persona_id"],
            ["personas.id"],
            name=op.f("fk_generation_feedback_persona_id_personas"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_generation_feedback")),
    )
    op.create_index(
        op.f("ix_generation_feedback_generation_id"),
        "generation_feedback",
        ["generation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_generation_feedback_persona_id"),
        "generation_feedback",
        ["persona_id"],
        unique=False,
    )
    op.create_table(
        "notification_settings",
        sa.Column("persona_id", sa.String(length=30), nullable=False),
        sa.Column("morning_briefing_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["persona_id"],
            ["personas.id"],
            name=op.f("fk_notification_settings_persona_id_personas"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("persona_id", name=op.f("pk_notification_settings")),
    )
    op.create_table(
        "onboarding_profiles",
        sa.Column("persona_id", sa.String(length=30), nullable=False),
        sa.Column("skin_concern_ids", sa.JSON(), nullable=False),
        sa.Column("birth_year", sa.Integer(), nullable=True),
        sa.Column("menstrual_cycle_tracking", sa.Boolean(), nullable=True),
        sa.Column("onboarding_completed", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["persona_id"],
            ["personas.id"],
            name=op.f("fk_onboarding_profiles_persona_id_personas"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("persona_id", name=op.f("pk_onboarding_profiles")),
    )
    op.create_table(
        "persona_cosmetics",
        sa.Column("persona_id", sa.String(length=30), nullable=False),
        sa.Column("image_key", sa.String(length=500), nullable=True),
        sa.Column("brand", sa.String(length=100), nullable=False),
        sa.Column("product_name", sa.String(length=200), nullable=False),
        sa.Column("product_type", sa.String(length=30), nullable=True),
        sa.Column("ingredients_raw", sa.JSON(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["persona_id"],
            ["personas.id"],
            name=op.f("fk_persona_cosmetics_persona_id_personas"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_persona_cosmetics")),
    )
    op.create_index(
        op.f("ix_persona_cosmetics_deleted_at"), "persona_cosmetics", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_persona_cosmetics_persona_id"), "persona_cosmetics", ["persona_id"], unique=False
    )
    op.create_table(
        "reports",
        sa.Column("persona_id", sa.String(length=30), nullable=False),
        sa.Column("period_days", sa.Integer(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("locale", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("period", sa.JSON(), nullable=True),
        sa.Column("summary", sa.String(length=500), nullable=True),
        sa.Column("observations", sa.JSON(), nullable=True),
        sa.Column("patterns", sa.JSON(), nullable=True),
        sa.Column("recommendations", sa.JSON(), nullable=True),
        sa.Column("limitations", sa.String(length=300), nullable=True),
        sa.Column("safety_status", sa.String(length=20), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["persona_id"],
            ["personas.id"],
            name=op.f("fk_reports_persona_id_personas"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
    )
    op.create_index(op.f("ix_reports_persona_id"), "reports", ["persona_id"], unique=False)
    op.create_table(
        "skin_scans",
        sa.Column("persona_id", sa.String(length=30), nullable=False),
        sa.Column("capture_method", sa.String(length=20), nullable=False),
        sa.Column("image_key", sa.String(length=500), nullable=True),
        sa.Column("questionnaire_version", sa.String(length=10), nullable=True),
        sa.Column("answers", sa.JSON(), nullable=True),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lighting_ok", sa.Boolean(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("lower_accuracy", sa.Boolean(), nullable=False),
        sa.Column("scores", sa.JSON(), nullable=True),
        sa.Column("confidence", sa.JSON(), nullable=True),
        sa.Column("delta_vs_baseline", sa.JSON(), nullable=True),
        sa.Column("delta_vs_previous", sa.JSON(), nullable=True),
        sa.Column("limitation_notice", sa.String(length=300), nullable=True),
        sa.Column("failure_code", sa.String(length=50), nullable=True),
        sa.Column("failure_message", sa.String(length=300), nullable=True),
        sa.Column("failure_retryable", sa.Boolean(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["persona_id"],
            ["personas.id"],
            name=op.f("fk_skin_scans_persona_id_personas"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skin_scans")),
    )
    op.create_index(op.f("ix_skin_scans_persona_id"), "skin_scans", ["persona_id"], unique=False)
    op.create_table(
        "sos_sessions",
        sa.Column("persona_id", sa.String(length=30), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["persona_id"],
            ["personas.id"],
            name=op.f("fk_sos_sessions_persona_id_personas"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sos_sessions")),
    )
    op.create_index(
        op.f("ix_sos_sessions_persona_id"), "sos_sessions", ["persona_id"], unique=False
    )
    op.create_table(
        "sos_messages",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("persona_id", sa.String(length=30), nullable=False),
        sa.Column("message", sa.String(length=1000), nullable=False),
        sa.Column("reply_type", sa.String(length=20), nullable=False),
        sa.Column("reply", sa.String(length=1000), nullable=False),
        sa.Column("matched_faq", sa.JSON(), nullable=True),
        sa.Column("referenced_cosmetic_ids", sa.JSON(), nullable=False),
        sa.Column("safety_flag", sa.String(length=50), nullable=True),
        sa.Column("expert_referral_suggested", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["persona_id"],
            ["personas.id"],
            name=op.f("fk_sos_messages_persona_id_personas"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sos_sessions.id"],
            name=op.f("fk_sos_messages_session_id_sos_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sos_messages")),
    )
    op.create_index(
        op.f("ix_sos_messages_persona_id"), "sos_messages", ["persona_id"], unique=False
    )
    op.create_index(
        op.f("ix_sos_messages_session_id"), "sos_messages", ["session_id"], unique=False
    )
    # NOTE: alembic autogenerate also proposed alter_column/drop_constraint/index
    # changes to the pre-existing care_contexts/care_routines/cosmetics/users
    # tables here. Those are SQLite reflection artifacts (NOT NULL and unique
    # index vs. unique constraint representation differences) with no matching
    # model change — intentionally omitted from this migration.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sos_messages_session_id"), table_name="sos_messages")
    op.drop_index(op.f("ix_sos_messages_persona_id"), table_name="sos_messages")
    op.drop_table("sos_messages")
    op.drop_index(op.f("ix_sos_sessions_persona_id"), table_name="sos_sessions")
    op.drop_table("sos_sessions")
    op.drop_index(op.f("ix_skin_scans_persona_id"), table_name="skin_scans")
    op.drop_table("skin_scans")
    op.drop_index(op.f("ix_reports_persona_id"), table_name="reports")
    op.drop_table("reports")
    op.drop_index(op.f("ix_persona_cosmetics_persona_id"), table_name="persona_cosmetics")
    op.drop_index(op.f("ix_persona_cosmetics_deleted_at"), table_name="persona_cosmetics")
    op.drop_table("persona_cosmetics")
    op.drop_table("onboarding_profiles")
    op.drop_table("notification_settings")
    op.drop_index(op.f("ix_generation_feedback_persona_id"), table_name="generation_feedback")
    op.drop_index(op.f("ix_generation_feedback_generation_id"), table_name="generation_feedback")
    op.drop_table("generation_feedback")
    op.drop_index(op.f("ix_daily_metrics_persona_id"), table_name="daily_metrics")
    op.drop_table("daily_metrics")
    op.drop_index(op.f("ix_consents_persona_id"), table_name="consents")
    op.drop_table("consents")
    op.drop_index(op.f("ix_briefings_persona_id"), table_name="briefings")
    op.drop_table("briefings")
    op.drop_table("recommendation_products")
    op.drop_table("personas")
    op.drop_table("knowledge_indexes")
    op.drop_table("knowledge_documents")
    op.drop_table("ingredients")
    op.drop_index(op.f("ix_idempotency_records_subject"), table_name="idempotency_records")
    op.drop_index(op.f("ix_idempotency_records_scope"), table_name="idempotency_records")
    op.drop_table("idempotency_records")
    op.drop_index(op.f("ix_generations_persona_id"), table_name="generations")
    op.drop_table("generations")
    # ### end Alembic commands ###
